default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: postgres
  pool: 5

development:
  <<: *default
  database: psm_development
test:
  <<: *default
  database: psm_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: 5